global:
  scrape_interval: 5s
  external_labels:
    monitor: 'node'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['192.168.1.60:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['192.168.1.60:9100']

