- name: alert_rules
    rules:
      - alert: InstanceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Instance [{{ $labels.instance }}] down"
          description: "[{{ $labels.instance }}] of job [{{ $labels.job }}] has been down for more than 1 minute."


      - alert: DiskSpaceFree10Percent
    expr: node_filesystem_free_percent <= 10
    labels:
      severity: warning
    annotations:
      summary: "Instance [{{ $labels.instance }}] has 10% or less Free disk space"
      description: "[{{ $labels.instance }}] has only {{ $value }}% or less free."

 Action Required:
      Please investigate and take appropriate action to address the low disk space issue on the affected instance.
       
       - alert: HighCpuUsage
    expr: node_cpu_seconds_total{mode="idle"} < 500
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High CPU Usage Detected"
    description: "CPU usage is below 50% for 5 minutes."
